spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:/changelog/migration/
  datasource:
    hikari:
      max-lifetime: 30000
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath*:/changelog/changelog_dev.yaml
  sql:
    init:
      platform: postgres
  jpa:
    show-sql: true
cloud:
  aws:
    region:
      static: ireland
      auto: false
server:
  port: 8081
  servlet:
    context-path: /api
stripe:
  key: ${STRIPE_API_KEY:}
integrations:
  countries:
    base-url: https://restcountries.com
    asic-authentication-username:
    asic-authentication-password:
    resilience:
      timeout-in-seconds: 3
      retry-delay-in-seconds: 1
      number-of-retries: 2
      circuit-breaker:
        failure-rate-threshold: 50
        seconds-in-open-state: 15
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 5
