spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:/changelog/migration/
  datasource:
    url: jdbc:postgresql://localhost:5432/company-data
    username: CHANGE_ME
    password: CHANGE_ME
  liquibase:
    change-log: classpath*:/changelog/changelog_dev.yaml
  sql:
    init:
      platform: postgres

