version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'EdvinasA/OnlineStore-Java-Back-End'
    revision: develop
    git: github
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: online-store-java-back-end
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
