spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:/changelog/migration/
  datasource:
    hikari:
      max-lifetime: 30000
    url:
    username: postgres
    password: admin
  liquibase:
    change-log: classpath*:/changelog/changelog_dev.yaml
  sql:
    init:
      platform: postgres
cloud:
  aws:
    region:
      static: ireland
      auto: false
server:
  port: 8888
  servlet:
    context-path: /api
